jdk:
  - openjdk8
services:
  - docker 

before_install:
  - docker pull codingene/nextflow-base:dev
  - docker tag codingene/nextflow-base:dev codingene/nextflow-base:0.1.0

install:
  - sudo apt-get -qq update
  - sudo apt-get -qq -y install graphviz realpath
script:
  - curl -fsSL get.nextflow.io | bash
  - ./nextflow run . -with-docker -with-report travis_built_report.html

addons:
  artifacts:
    paths:
    - $HOME/build/codingene/nextflow-base/travis_built_report.html

deploy:
  - provider: s3
  - access_key_id: $ARTIFACTS_KEY
  - secret_access_key: $ARTIFACTS_SECRET
  - bucket: $ARTIFACTS_BUCKET
  - skip_cleanup: true
  - acl: public_rea