version: 2.0
jobs:
  build:
    machine:
      pre:
        - curl -sSL https://s3.amazonaws.com/circle-downloads/install-circleci-docker.sh | bash -s -- 1.10.0
      java:
        version: oraclejdk8
      services:
        - docker
    steps:
      - checkout    
      - run:
          name: Get Nextflow and required tools
          command: |
            curl -fsSL get.nextflow.io | bash
            #apt install -y zip unzip
      - run:    
          name: Run the workflow
          command: |
            ./nextflow run main.nf -profile test,docker
          no_output_timeout: 1500
      - store_artifacts:
          path: test_out
