# Copied from nf-core
name: nextflow-base CI
# This workflow is triggered on pushes and PRs to the repository.
on: [push, pull_request]  

jobs:
  test:
    runs-on: ubuntu-18.04
    strategy:
      matrix:
        # Nextflow versions: check pipeline minimum and current latest
        nxf_ver: ['19.10.0','']
        #options: ["test,docker", "test_long,docker --assembler canu", "test_long_miniasm,docker", "test_hybrid,docker", "test,docker --annotation_tool dfast" ]
    steps:
      - uses: actions/checkout@v1
      - name: Install Nextflow
        run: |
          export NXF_VER=${{ matrix.nxf_ver }}
          wget -qO- get.nextflow.io | bash
          sudo mv nextflow /usr/local/bin/
      - name: Download and tag image
        run: |
          docker pull codingene/nextflow-base:latest
          docker tag codingene/nextflow-base:latest codingene/nextflow-base:0.0.1
      - name: Run tests
        run: |
          nextflow run ${GITHUB_WORKSPACE} -with-docker
          
